languageCode = 'en-us'
title        = 'Sethu'
theme        = 'sethu'

[params.images]
reviews  = 'images/reviews'
trustees = 'images/trustees'
team     = 'images/team'


[module]
[module.hugoVersion]
extended = false
min      = "0.147.8"

[markup]
[markup.goldmark]
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true

[taxonomies]
author = 'authors'
topic = 'topics'